apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-k8s-namespace
  name: auth-engine
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: auth-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-k8s-namespace
  name: auth-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-engine
  template:
    metadata:
      labels:
        app: auth-engine
    spec:
      # imagePullSecrets:
      #   - name: registry-secret
      containers:
        - name: auth-engine
          image: newerton/auth-engine:latest
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: auth-engine-k8s-secret
